// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameCredentials(arg1) {
  return window['go']['backend']['AuthService']['GetGameCredentials'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['backend']['AuthService']['GetProfile'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['backend']['AuthService']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['backend']['AuthService']['Logout'](arg1);
}

export function Refresh(arg1) {
  return window['go']['backend']['AuthService']['Refresh'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['backend']['AuthService']['Register'](arg1, arg2, arg3);
}

export function UpdateProfileImage(arg1, arg2) {
  return window['go']['backend']['AuthService']['UpdateProfileImage'](arg1, arg2);
}
