// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Login(arg1:string,arg2:string):Promise<backend.AuthResponse>;

export function Logout():Promise<void>;

export function Refresh(arg1:string):Promise<backend.AuthResponse>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<backend.AuthResponse>;
