// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['backend']['PatchingService']['CheckForUpdates'](arg1);
}

export function DownloadUpdates(arg1, arg2) {
  return window['go']['backend']['PatchingService']['DownloadUpdates'](arg1, arg2);
}

export function RepairGameFiles(arg1) {
  return window['go']['backend']['PatchingService']['RepairGameFiles'](arg1);
}
