// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckForUpdates(arg1:string):Promise<backend.UpdateCheckResult>;

export function DownloadUpdates(arg1:Array<backend.FileHash>,arg2:string):Promise<void>;

export function RepairGameFiles(arg1:string):Promise<void>;
